### ISSUE TITLE
registers serialization to file

### ISSUE THREAD

**Issue by apmanol** [kvasir-io/Kvasir#111]
Grats for the excellent implementation of the library.

One question that came up, after studying the use of it, is how we can export some setup `variable name` / `value` to a file and reload it again sometime later.

Do you have any suggestions  about it or the implementation scope doesn't contain such issues?

**Comment by odinthenerd** [comment]
That is something that we will look into in the future. Its not on our radar right now but nice to see interest in it. Current focus is identifying and implementing things which can freeze now and not get in the way of future expansion of the library.

**Comment by apmanol** [comment]
Thanks a lot for the response.
