### ISSUE TITLE
SFR definitions should use fixed size types

### ISSUE THREAD

**Issue by LegalizeAdulthood** [kvasir-io/Kvasir#115]
Since SFRs have a fixed width, the register definitions in Kvasir should use the fixed length types such as `std::uint8_t`, `std::uint16_t` and so-on from `<cstdint>`.  This would make the definitions of the SFRs more explicit in their requirements instead of using `unsigned short` or `unsigned` as the defining type.

**Comment by odinthenerd** [comment]
yes, I agree, stupid design decision on my part ;)
