### ISSUE TITLE
Where is KVASIR_START/KVASIR_CLOCK?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [kvasir-io/Kvasir#117]
The videos and the wiki both mention these, but I don't find them anywhere in the code.

What is the current architecture for startup code?

**Comment by odinthenerd** [comment]
it turns out that unified clock trees are about two orders of magnitude more complex than I originally expected so this feature has died. baring some genius idea or 10 man year investment I do not see this being possible.

**Comment by LegalizeAdulthood** [comment]
How about the startup code via KVASIR_START?

**Comment by odinthenerd** [comment]
that's also out of scope, at least for now

**Comment by LegalizeAdulthood** [comment]
We should delete this wiki page then :)

https://github.com/kvasir-io/Kvasir/wiki/Startup-code

**Comment by odinthenerd** [comment]
agree, done.
