### ISSUE TITLE
How to deal with Dont-Touch Registers?

### ISSUE THREAD

**Issue by MaxClerkwell** [kvasir-io/Kvasir#29]
While writing Chipfile of UM10736 I found register 0x4007 4124 
bits 11:0 and 31:14 have to be written back as read. 
what does an action like this look like? should it be available at all to touch them? how can we secure that they are never touched? 

->lpc15xx manual
->chapter 3.6.32
->syscon::flashcfg

![havealookj](https://cloud.githubusercontent.com/assets/10761141/8827903/a2923fbc-308f-11e5-813e-24c8a71ff716.jpg)

**Comment by odinthenerd** [comment]
just don't include them at all in any mask (especially not in the tempting reserved mask) and do not provide BitLocations to them (well read would technically be ok I don't see any reason.
