### ISSUE TITLE
Should ChipFromSvdGenerator get his own repo.

### ISSUE THREAD

**Issue by CvRXX** [kvasir-io/Kvasir#85]
Because of the fact that the CFSG is a tool and not part of the kvasir registery abstraction I think it should have its own repo. In this way we could also  version it as a standalone tool. Would also enable other users to use it for different purposes.

**Comment by odinthenerd** [comment]
Yes I agree, we should do this in its own lib

**Comment by CvRXX** [comment]
It has now, if the new version is finished we could remove it in the next version of kvasir registers.
